
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MedicalClinic {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainGUI : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme custom;
        
        private Terminal.Gui.Button buttonHelp;
        
        private Terminal.Gui.Button buttonQuit;
        
        private Terminal.Gui.Label searchBarLabel;
        
        private Terminal.Gui.TextField searchBar;
        
        private Terminal.Gui.Button buttonHelp2;
        
        private Terminal.Gui.Label label_PatientList;
        
        private Terminal.Gui.Label label_PatientList2;
        
        private Terminal.Gui.Button buttonAdd;
        
        private Terminal.Gui.Button buttonAddRandom;
        
        private Terminal.Gui.Button buttonRemoveAll;
        
        private Terminal.Gui.TableView patientList;
        
        private void InitializeComponent() {
            this.patientList = new Terminal.Gui.TableView();
            this.buttonRemoveAll = new Terminal.Gui.Button();
            this.buttonAddRandom = new Terminal.Gui.Button();
            this.buttonAdd = new Terminal.Gui.Button();
            this.label_PatientList2 = new Terminal.Gui.Label();
            this.label_PatientList = new Terminal.Gui.Label();
            this.buttonHelp2 = new Terminal.Gui.Button();
            this.searchBar = new Terminal.Gui.TextField();
            this.searchBarLabel = new Terminal.Gui.Label();
            this.buttonQuit = new Terminal.Gui.Button();
            this.buttonHelp = new Terminal.Gui.Button();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.custom = new Terminal.Gui.ColorScheme();
            this.custom.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray);
            this.custom.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray);
            this.custom.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.custom.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.custom.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.tgDefault;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Title = "";
            this.buttonHelp.Width = 8;
            this.buttonHelp.Height = 1;
            this.buttonHelp.X = Pos.Percent(90f);
            this.buttonHelp.Y = 0;
            this.buttonHelp.Visible = true;
            this.buttonHelp.Data = "buttonHelp";
            this.buttonHelp.Text = "Help";
            this.buttonHelp.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonHelp.IsDefault = false;
            this.Add(this.buttonHelp);
            this.buttonQuit.Width = 8;
            this.buttonQuit.Height = 1;
            this.buttonQuit.X = Pos.Percent(95f);
            this.buttonQuit.Y = 0;
            this.buttonQuit.Visible = true;
            this.buttonQuit.Data = "buttonQuit";
            this.buttonQuit.Text = "Quit";
            this.buttonQuit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonQuit.IsDefault = false;
            this.Add(this.buttonQuit);
            this.searchBarLabel.Width = 10;
            this.searchBarLabel.Height = 1;
            this.searchBarLabel.X = 0;
            this.searchBarLabel.Y = 2;
            this.searchBarLabel.Visible = true;
            this.searchBarLabel.Data = "searchBarLabel";
            this.searchBarLabel.Text = "SearchBar:";
            this.searchBarLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.searchBarLabel);
            this.searchBar.Width = Dim.Percent(90f);
            this.searchBar.Height = 1;
            this.searchBar.X = 10;
            this.searchBar.Y = 2;
            this.searchBar.Visible = true;
            this.searchBar.Secret = false;
            this.searchBar.Data = "searchBar";
            this.searchBar.Text = "";
            this.searchBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.searchBar);
            this.buttonHelp2.Width = 8;
            this.buttonHelp2.Height = 1;
            this.buttonHelp2.X = Pos.Percent(95f);
            this.buttonHelp2.Y = 2;
            this.buttonHelp2.Visible = true;
            this.buttonHelp2.Data = "buttonHelp2";
            this.buttonHelp2.Text = "Help";
            this.buttonHelp2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonHelp2.IsDefault = false;
            this.Add(this.buttonHelp2);
            this.label_PatientList.Width = 137;
            this.label_PatientList.Height = 3;
            this.label_PatientList.X = 0;
            this.label_PatientList.Y = 6;
            this.label_PatientList.Visible = true;
            this.label_PatientList.Data = "label_PatientList";
            this.label_PatientList.Text = "Patient List";
            this.label_PatientList.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.label_PatientList);
            this.label_PatientList2.Width = Dim.Fill(0);
            this.label_PatientList2.Height = 3;
            this.label_PatientList2.X = 0;
            this.label_PatientList2.Y = 6;
            this.label_PatientList2.Visible = false;
            this.label_PatientList2.Data = "label_PatientList2";
            this.label_PatientList2.Text = "Patient List";
            this.label_PatientList2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.label_PatientList2);
            this.buttonAdd.Width = 7;
            this.buttonAdd.Height = 1;
            this.buttonAdd.X = 1;
            this.buttonAdd.Y = 8;
            this.buttonAdd.Visible = true;
            this.buttonAdd.Data = "buttonAdd";
            this.buttonAdd.Text = "Add";
            this.buttonAdd.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonAdd.IsDefault = false;
            this.Add(this.buttonAdd);
            this.buttonAddRandom.Width = 14;
            this.buttonAddRandom.Height = 1;
            this.buttonAddRandom.X = 10;
            this.buttonAddRandom.Y = 8;
            this.buttonAddRandom.Visible = true;
            this.buttonAddRandom.Data = "buttonAddRandom";
            this.buttonAddRandom.Text = "Add random";
            this.buttonAddRandom.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonAddRandom.IsDefault = false;
            this.Add(this.buttonAddRandom);
            this.buttonRemoveAll.Width = 14;
            this.buttonRemoveAll.Height = 1;
            this.buttonRemoveAll.X = 26;
            this.buttonRemoveAll.Y = 8;
            this.buttonRemoveAll.Visible = true;
            this.buttonRemoveAll.Data = "buttonRemoveAll";
            this.buttonRemoveAll.Text = "Remove all";
            this.buttonRemoveAll.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonRemoveAll.IsDefault = false;
            this.Add(this.buttonRemoveAll);
            this.patientList.Width = Dim.Percent(100f);
            this.patientList.Height = Dim.Percent(85f);
            this.patientList.X = 0;
            this.patientList.Y = 9;
            this.patientList.Visible = true;
            this.patientList.ColorScheme = this.tgDefault;
            this.patientList.Data = "patientList";
            this.patientList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.patientList.FullRowSelect = true;
            this.patientList.Style.AlwaysShowHeaders = true;
            this.patientList.Style.ExpandLastColumn = true;
            this.patientList.Style.InvertSelectedCellFirstCharacter = false;
            this.patientList.Style.ShowHorizontalHeaderOverline = true;
            this.patientList.Style.ShowHorizontalHeaderUnderline = true;
            this.patientList.Style.ShowVerticalCellLines = true;
            this.patientList.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable patientListTable;
            patientListTable = new System.Data.DataTable();
            System.Data.DataColumn patientListTableFirstName;
            patientListTableFirstName = new System.Data.DataColumn();
            patientListTableFirstName.ColumnName = "First Name";
            patientListTable.Columns.Add(patientListTableFirstName);
            System.Data.DataColumn patientListTableLastName;
            patientListTableLastName = new System.Data.DataColumn();
            patientListTableLastName.ColumnName = "Last Name";
            patientListTable.Columns.Add(patientListTableLastName);
            System.Data.DataColumn patientListTableColumn2;
            patientListTableColumn2 = new System.Data.DataColumn();
            patientListTableColumn2.ColumnName = "Column 2";
            patientListTable.Columns.Add(patientListTableColumn2);
            System.Data.DataColumn patientListTableColumn3;
            patientListTableColumn3 = new System.Data.DataColumn();
            patientListTableColumn3.ColumnName = "Column 3";
            patientListTable.Columns.Add(patientListTableColumn3);
            System.Data.DataColumn patientListTableMyDataColumn;
            patientListTableMyDataColumn = new System.Data.DataColumn();
            patientListTableMyDataColumn.ColumnName = "MyDataColumn";
            patientListTable.Columns.Add(patientListTableMyDataColumn);
            System.Data.DataColumn patientListTableMyDataColumn2;
            patientListTableMyDataColumn2 = new System.Data.DataColumn();
            patientListTableMyDataColumn2.ColumnName = "MyDataColumn2";
            patientListTable.Columns.Add(patientListTableMyDataColumn2);
            System.Data.DataColumn patientListTableMyDataColumn3;
            patientListTableMyDataColumn3 = new System.Data.DataColumn();
            patientListTableMyDataColumn3.ColumnName = "MyDataColumn3";
            patientListTable.Columns.Add(patientListTableMyDataColumn3);
            System.Data.DataColumn patientListTableMyDataColumn4;
            patientListTableMyDataColumn4 = new System.Data.DataColumn();
            patientListTableMyDataColumn4.ColumnName = "MyDataColumn4";
            patientListTable.Columns.Add(patientListTableMyDataColumn4);
            this.patientList.Table = patientListTable;
            this.Add(this.patientList);
        }
    }
}
