version: "3.8"

# DB
services:
  postgres1:
    image: postgres
    container_name: postgres1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1