version: "3.8"

services:
  # DB
  postgres1:
    image: postgres
    container_name: postgres1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1

  # Redis
#   cache:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - '6379:6379'
#     command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     volumes: 
#       - cache:/data
# volumes:
#   cache:
#     driver: local
